version: "3"
networks:
  eureka-net:
    driver: bridge
services:
  service-eureka:
    image: amourabarreto/microservices:service-registry
    networks:
      eureka-net:
    ports:
      - "8761:8761"
  service-gateway:
    image: amourabarreto/microservices:service-gateway
    networks:
      eureka-net:
    ports:
      - '8080:8080'
    environment:
      URL-EUREKA-SERVER: http://service-eureka:8761/eureka
    depends_on:
      - service-eureka
  #  links:
   #   - 'service-eureka'