server:
  port: 8080
spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE/
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://EAD-COURSE-SERVICE/
          predicates:
            - Path=/ead-course/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${URL-EUREKA-SERVER}
      #defaultZone: 'http://localhost:8761/eureka'
  instance:
    prefer-ip-address: true
    #hostname: ${HOST_NAME}
    #hostname: localhost